# Generated by Django 2.0.3 on 2018-05-10 19:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, null=True)),
                ('local_score', models.SmallIntegerField(blank=True, null=True)),
                ('visitor_score', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(choices=[('KO-1', 'KO-1'), ('KO-2', 'KO-2'), ('KO-4', 'KO-4'), ('KO-8', 'KO-8'), ('KO-16', 'KO-16'), ('POS-3', 'POS-3'), ('POS-5', 'POS-5'), ('POS-6', 'POS-6'), ('POS-7', 'POS-7'), ('POS-8', 'POS-8'), ('POS-9', 'POS-9'), ('POS-10', 'POS-10'), ('POS-11', 'POS-11'), ('POS-12', 'POS-12'), ('POS-13', 'POS-13'), ('POS-15', 'POS-15'), ('POS-16', 'POS-16'), ('POS-18', 'POS-18'), ('POS-20', 'POS-20'), ('Division', 'Division'), ('Pool-A', 'Pool-A'), ('Pool-B', 'Pool-B'), ('Pool-C', 'Pool-C'), ('Pool-D', 'Pool-D'), ('Pool-E', 'Pool-E'), ('Pool-F', 'Pool-F'), ('Liga', 'Liga')], default='Pool-A', max_length=32)),
                ('number_teams', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('category', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze'), ('Wood', 'Wood')], default='Gold', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='PadelResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local1', models.SmallIntegerField(blank=True, null=True)),
                ('local2', models.SmallIntegerField(blank=True, null=True)),
                ('local3', models.SmallIntegerField(blank=True, null=True)),
                ('local4', models.SmallIntegerField(blank=True, null=True)),
                ('local5', models.SmallIntegerField(blank=True, null=True)),
                ('visitor1', models.SmallIntegerField(blank=True, null=True)),
                ('visitor2', models.SmallIntegerField(blank=True, null=True)),
                ('visitor3', models.SmallIntegerField(blank=True, null=True)),
                ('visitor4', models.SmallIntegerField(blank=True, null=True)),
                ('visitor5', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('born', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', None)], default='U', max_length=1, null=True)),
            ],
            options={
                'ordering': ['gender', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Person')),
            ],
            options={
                'ordering': ['person'],
            },
        ),
        migrations.CreateModel(
            name='PlayerStadistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('mvp', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('played', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('division', models.CharField(choices=[('MXO', 'Mixed Open'), ('MO', 'Mens Open'), ('WO', 'Womens Open'), ('SMX', 'Senior Mix Open'), ('M30', 'Mens 30'), ('M40', 'Mens 40'), ('W27', 'Women 27')], max_length=3)),
                ('players', models.ManyToManyField(through='tournaments.Player', to='tournaments.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PADEL', 'PADEL'), ('TOUCH', 'TOUCH')], default='PADEL', max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('division', models.CharField(blank=True, choices=[('MXO', 'Mixed Open'), ('MO', 'Mens Open'), ('WO', 'Womens Open'), ('SMX', 'Senior Mix Open'), ('M30', 'Mens 30'), ('M40', 'Mens 40'), ('W27', 'Women 27')], max_length=3, null=True)),
                ('teams', models.ManyToManyField(blank=True, to='tournaments.Team')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='playerstadistic',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.Tournament'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='tournaments_played',
            field=models.ManyToManyField(blank=True, to='tournaments.Tournament'),
        ),
        migrations.AddField(
            model_name='game',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.GameField'),
        ),
        migrations.AddField(
            model_name='game',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local', to='tournaments.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.GameRound'),
        ),
        migrations.AddField(
            model_name='game',
            name='result_padel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.PadelResult'),
        ),
        migrations.AddField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament'),
        ),
        migrations.AddField(
            model_name='game',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitor', to='tournaments.Team'),
        ),
    ]
