# Generated by Django 2.0.3 on 2018-05-10 13:43

import anmeldung.models
import anmeldung.validators
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=30)),
                ('postcode', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(99), django.core.validators.MaxValueValidator(1000000)])),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=24)),
                ('address', models.CharField(blank=True, max_length=120)),
                ('indoor_courts', models.PositiveIntegerField()),
                ('outdoor_courts', models.PositiveIntegerField()),
                ('logo', models.ImageField(default='default.jpg', upload_to=anmeldung.models.club_directory_path)),
                ('cover_photo', models.ImageField(default='pista.jpg', upload_to=anmeldung.models.club_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='PadelPerson',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tournaments.Person')),
                ('last_name2', models.CharField(blank=True, max_length=24)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=64, verbose_name='Phone')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=32, verbose_name='City')),
                ('birthplace', models.CharField(max_length=32, verbose_name='Birth place')),
                ('ranking_points', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('photo', models.ImageField(default='Cool-Male-Avatars-06.png', upload_to=anmeldung.models.player_directory_path)),
                ('policy_read', models.BooleanField(default=False, validators=[anmeldung.validators.policy_read_validator])),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='anmeldung.Club')),
            ],
            bases=('tournaments.person',),
        ),
        migrations.CreateModel(
            name='PadelTournament',
            fields=[
                ('tournament_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tournaments.Tournament')),
                ('padel_serie', models.CharField(choices=[('GPS-100', 'GPS-100'), ('GPS-250', 'GPS-250'), ('GPS-500', 'GPS-500'), ('GPS-1000', 'GPS-1000'), ('GPS-1200', 'GPS-1200'), ('GPS-WOMEN', 'GPS-WOMEN')], default='GPS-500', max_length=20)),
                ('padel_category', models.CharField(choices=[('Herren A', 'Herren A'), ('Herren B', 'Herren B'), ('Damen', 'Damen'), ('Mixed', 'Mixed'), ('Senioren', 'Senioren'), ('Junioren', 'Junioren')], default='Herren A', max_length=20)),
                ('signup', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='anmeldung.Club')),
            ],
            bases=('tournaments.tournament',),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('policy_read', models.BooleanField(default=False, validators=[anmeldung.validators.policy_read_validator])),
                ('player_a', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_a', to='anmeldung.PadelPerson')),
                ('player_b', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_b', to='anmeldung.PadelPerson')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tournaments.Tournament')),
            ],
        ),
    ]
