# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-15 15:12
from __future__ import unicode_literals

import anmeldung.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Herren A', 'Herren A'), ('Herren B', 'Herren B'), ('Damen', 'Damen'), ('Mixed', 'Mixed'), ('Senioren', 'Senioren'), ('Junioren', 'Junioren')], max_length=16)),
                ('forename', models.CharField(max_length=24, verbose_name='First Name')),
                ('surname', models.CharField(max_length=24, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=64, verbose_name='Phone')),
                ('city', models.CharField(max_length=32, verbose_name='City')),
                ('club', models.CharField(max_length=32, verbose_name='Club')),
                ('birthplace', models.CharField(max_length=32, verbose_name='Birth place')),
                ('birthdate', models.DateTimeField(verbose_name='Birthday')),
                ('ranking_points', models.PositiveIntegerField(verbose_name='Ranking Points')),
                ('policy_read', models.BooleanField(default=True, validators=[anmeldung.validators.policy_read_validator])),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('GPS-100', 'GPS-100'), ('GPS-250', 'GPS-250'), ('GPS-500', 'GPS-500'), ('GPS-1000', 'GPS-1000'), ('GPS-1200', 'GPS-1200')], max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='tournament_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anmeldung.Tournament'),
        ),
    ]
