# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-16 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldung', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=24, verbose_name='First Name')),
                ('surname', models.CharField(max_length=24, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=64, verbose_name='Phone')),
                ('city', models.CharField(max_length=32, verbose_name='City')),
                ('club', models.CharField(max_length=32, verbose_name='Club')),
                ('birthplace', models.CharField(max_length=32, verbose_name='Birth place')),
                ('birthdate', models.DateTimeField(verbose_name='Birthday')),
                ('ranking_points', models.PositiveIntegerField(verbose_name='Ranking Points')),
            ],
        ),
        migrations.RemoveField(
            model_name='registration',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='birthplace',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='city',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='club',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='forename',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='ranking_points',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='surname',
        ),
    ]
