# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-16 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldung', '0003_auto_20180116_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='tournament_name',
            new_name='tournament',
        ),
    ]
