# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-16 14:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldung', '0004_auto_20180116_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='player_a',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='player_a', to='anmeldung.Player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='player_b',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='player_b', to='anmeldung.Player'),
            preserve_default=False,
        ),
    ]
