# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-16 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldung', '0005_auto_20180116_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='category',
        ),
        migrations.AddField(
            model_name='tournament',
            name='serie',
            field=models.CharField(choices=[('GPS-100', 'GPS-100'), ('GPS-250', 'GPS-250'), ('GPS-500', 'GPS-500'), ('GPS-1000', 'GPS-1000'), ('GPS-1200', 'GPS-1200')], default='Herren A', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='category',
            field=models.CharField(choices=[('Herren A', 'Herren A'), ('Herren B', 'Herren B'), ('Damen', 'Damen'), ('Mixed', 'Mixed'), ('Senioren', 'Senioren'), ('Junioren', 'Junioren')], default='GPS-500', max_length=20),
        ),
    ]
