# Generated by Django 2.0.1 on 2018-01-17 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldung', '0006_auto_20180116_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='player_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_a', to='anmeldung.Player'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='player_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_b', to='anmeldung.Player'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='anmeldung.Tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='category',
            field=models.CharField(choices=[('Herren A', 'Herren A'), ('Herren B', 'Herren B'), ('Damen', 'Damen'), ('Mixed', 'Mixed'), ('Senioren', 'Senioren'), ('Junioren', 'Junioren')], default='Herren A', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='serie',
            field=models.CharField(choices=[('GPS-100', 'GPS-100'), ('GPS-250', 'GPS-250'), ('GPS-500', 'GPS-500'), ('GPS-1000', 'GPS-1000'), ('GPS-1200', 'GPS-1200')], default='GPS-500', max_length=20),
        ),
    ]
