# Generated by Django 2.0.1 on 2018-01-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldung', '0007_auto_20180117_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='signup',
            field=models.BooleanField(default=False),
        ),
    ]
