# Generated by Django 2.0.3 on 2018-03-17 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldung', '0008_tournament_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=24)),
                ('address', models.CharField(blank=True, max_length=120)),
                ('indoor_courts', models.PositiveIntegerField()),
                ('outdoor_courts', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='anmeldung.Club'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='anmeldung.Club'),
            preserve_default=False,
        ),
    ]
