# Generated by Django 2.0.3 on 2018-03-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldung', '0009_auto_20180317_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='surname2',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
