# Generated by Django 2.0.3 on 2018-03-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldung', '0012_player_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='foto',
            field=models.ImageField(default='favicon.jpg', upload_to='player_foto'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='serie',
            field=models.CharField(choices=[('GPS-100', 'GPS-100'), ('GPS-250', 'GPS-250'), ('GPS-500', 'GPS-500'), ('GPS-1000', 'GPS-1000'), ('GPS-1200', 'GPS-1200'), ('GPS-WOMEN', 'GPS-WOMEN')], default='GPS-500', max_length=20),
        ),
    ]
