# Generated by Django 2.0.3 on 2018-03-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldung', '0013_auto_20180323_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='cover_photo',
            field=models.ImageField(default='favicon.jpg', upload_to='club_cover_photo'),
        ),
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.ImageField(default='favicon.jpg', upload_to='club_logos'),
        ),
    ]
