# Generated by Django 2.0.3 on 2018-03-23 18:57

import anmeldung.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldung', '0014_auto_20180323_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='foto',
        ),
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(default='favicon.jpg', upload_to=anmeldung.models.player_directory_path),
        ),
        migrations.AlterField(
            model_name='club',
            name='cover_photo',
            field=models.ImageField(default='favicon.jpg', upload_to=anmeldung.models.club_directory_path),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(default='favicon.jpg', upload_to=anmeldung.models.club_directory_path),
        ),
    ]
