# Generated by Django 2.0.3 on 2018-03-23 23:06

import anmeldung.models
import anmeldung.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldung', '0015_auto_20180323_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='policy_read',
            field=models.BooleanField(default=True, validators=[anmeldung.validators.policy_read_validator]),
        ),
        migrations.AlterField(
            model_name='club',
            name='cover_photo',
            field=models.ImageField(default='pista.jpg', upload_to=anmeldung.models.club_directory_path),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(default='default.jpg', upload_to=anmeldung.models.club_directory_path),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(default='Cool-Male-Avatars-06.png', upload_to=anmeldung.models.player_directory_path),
        ),
        migrations.AlterField(
            model_name='player',
            name='ranking_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Ranking Points'),
        ),
    ]
