# Generated by Django 2.0.3 on 2018-03-25 20:27

import anmeldung.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldung', '0016_auto_20180323_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='policy_read',
            field=models.BooleanField(default=False, validators=[anmeldung.validators.policy_read_validator]),
        ),
        migrations.AlterField(
            model_name='registration',
            name='policy_read',
            field=models.BooleanField(default=False, validators=[anmeldung.validators.policy_read_validator]),
        ),
    ]
