# Generated by Django 2.0.3 on 2018-04-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldung', '0018_tournament_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='province',
            field=models.CharField(default='-', max_length=30),
            preserve_default=False,
        ),
    ]
